spring:
  application:
    name: vet-service
  datasource:
    url: jdbc:mysql://localhost:3306/petdb
    username: root
    password: Activa3g
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server: 
  port: 8000
